### ISSUE TITLE
新しいパラメータ形式への対応

### ISSUE THREAD

**Issue by yoidea** [kinc-shinshu/smat-teacher-client-new#12]
- [x] 問題編集画面
- [x] 問題追加画面
- [x] 問題一覧画面
- [x] ヘルパー

**Comment by arsley** [comment]
送るデータは
```json
{
  "smatex": "#{4}",
  "latex": "\\sqrt{4}",
  "answer": "2",
  "question_type": "Math"
}
```
みたいな感じになりそうかな？

**Comment by yoidea** [comment]
@arsley すっかり忘れてたけど、問題文と解答は両方共SmaTex形式で書かれているから、`answer`のフィールドも増やさないといけない気がする

**Comment by arsley** [comment]
@yoidea 
Oh my ...
`ans_smatex`, `ans_latex`とかで良さそう？
